name: Deploy Pages (placeholder)

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: No-op step
        run: echo "This is a placeholder workflow to satisfy YAML diagnostics."
